---
# Usage: http://ruhoh.com/usage/configure/

RuhohSpec: '1.0'
theme : 'simple'
production_url : http://prisoner.github.io

posts:
  permalink: /:year/:month/:day/:title.html
  summary_lines: 20
  latest: 10

pages:
  permalink: 'pretty'

# <img> tag auto insert config
# %s will be replace by "urlperfix / post name / img filename"
imgs:
  imgtag: '<img src="%s" alt="" width="600">'
  urlperfix: '{{urls.media}}/'
  localdir: 'media/'



